name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to AWS
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -e
            echo '1. Accès au répertoire...'
            cd ${{ secrets.WORK_DIR }}
            
            echo '2. Mise à jour du code...'
            git pull origin main
            
            echo '3. Nettoyage Docker...'
            docker-compose down --rmi all --volumes --remove-orphans
            
            echo '4. Reconstruction...'
            docker-compose up -d --build
          "

      - name: Cleanup
        if: always()
        run: rm -rf ~/.ssh