name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "|1|BASE64_HASH=|BASE64_HASH=" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Validate Permissions
        run: |
          echo "=== Vérification SSH ==="
          stat -c "%a %U:%G" ~/.ssh/id_rsa
          ssh-keygen -lf ~/.ssh/id_rsa | head -n1

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            sudo chown admin:admin /home/admin/.ssh/authorized_keys
            cd /home/admin/your_app_dir  # ← Modifiez ce chemin
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          "