name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_HOST }} ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI..." >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Debug SSH Configuration
        run: |
          echo "=== DEBUG ==="
          ls -la ~/.ssh
          head -n 3 ~/.ssh/id_rsa
          echo "============="

      - name: Test Connection
        run: ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} exit

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -x
            cd ${{ secrets.WORK_DIR }}
            git reset --hard
            git clean -fd
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          "